20242531 최은성

In [1]:
import numpy as np

a = np.ndarray(shape = (2, 2), dtype = int)
a

array([[-1593302754, -1450438745],
       [ 1884800939,   -95471970]])

In [2]:
a = np.ndarray([1, 2, 3], dtype = int)
a

array([[[-259744712,      32762,  -43033936],
        [       456, -259338216,      32762]]])

In [3]:
type(a)

numpy.ndarray

In [4]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(1, 2, 3)
3
int32


In [5]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

6
4
24


In [6]:
a.data

In [7]:
np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [11]:
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype = '<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [12]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [14]:
lang = np.array(['파이썬', '자바', '씨'], dtype = str)
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [16]:
a = np.array((1, 2, 3), dtype = float)
a

array([1., 2., 3.])

In [17]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

In [19]:
print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [20]:
print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [21]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [24]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.reshape(b, (2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [28]:
np.linspace(2.0, 3.0, retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [29]:
print((3 - 2) / (50 - 1))

0.02040816326530612


In [30]:
np.linspace(2.0, 3.0, endpoint = False, retstep = True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [31]:
print((3 - 2) / 50)

0.02


In [32]:
np.linspace(2.0, 3.0, num = 5, retstep = True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [33]:
np.linspace(2.0, 3.0, num = 5, endpoint = False, retstep = True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [34]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [35]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [36]:
np.linspace(0.1, 0.4, 3, endpoint = False)

array([0.1, 0.2, 0.3])

In [37]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

In [39]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [40]:
a.dtype

dtype('float64')

In [42]:
np.zeros((5, ), dtype = int)

array([0, 0, 0, 0, 0])

In [43]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [44]:
b.shape

(2, 1)

In [45]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.ones((2, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])