In [301]:
## 20242531 최은성

In [65]:
import numpy as np

a = np.arange(6).reshape(3, 2)
print(a)

b = np.arange(6, 12).reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [70]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [72]:
c = np.arange(20, 24).reshape(2, 2)
print(c)

[[20 21]
 [22 23]]


In [68]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [73]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [75]:
d = np.array([100, 200])
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [76]:
d = np.array([100, 200, 300])
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [78]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [79]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [80]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [81]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [82]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [86]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [88]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [90]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [91]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [92]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [93]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [94]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [95]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [96]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [97]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [98]:
np.column_stack == np.hstack

False

In [100]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [101]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [102]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [104]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [106]:
a = np.array([4., 2., 1.])
b = np.array([2., 8., 7.])
print(np.row_stack((a, b)))

[[4. 2. 1.]
 [2. 8. 7.]]


In [108]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [2. 8. 7.]]


In [109]:
np.row_stack == np.vstack

True

In [110]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [111]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [112]:
np.concatenate((a, b, c), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [113]:
np.concatenate((a, b, c), axis = None)

array([1, 2, 3, 4, 5, 6])

In [114]:
x = np.arange(6).reshape(2, 3)
print(x)
y = np.arange(10, 16).reshape(2, 3)
print(y)
z = np.arange(20, 24).reshape(2, 2)
print(z)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21]
 [22 23]]


In [116]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [117]:
np.concatenate((x, y, z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [118]:
np.concatenate((x, y), axis = 1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [119]:
np.concatenate((x, y, z), axis = 1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [121]:
np.concatenate((x, y), axis = None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [122]:
a = np.array([1, 2, 3])
print(a)
b = np.array([4, 5, 6])
print(b)

[1 2 3]
[4 5 6]


In [123]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.stack((a, b), axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [125]:
np.stack((a, b), axis = -1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [126]:
x = np.arange(6).reshape(2, 3)
print(x)
y = np.arange(10, 16).reshape(2, 3)
print(y)
z = np.arange(20, 26).reshape(2, 3)
print(z)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21 22]
 [23 24 25]]


In [129]:
ax0 = np.stack((x, y, z), axis = 0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [130]:
ax0.shape

(3, 2, 3)

In [133]:
ax1 = np.stack((x, y, z), axis = 1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [134]:
ax1.shape

(2, 3, 3)

In [136]:
ax2 = np.stack((x, y, z), axis = 2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [137]:
ax2.shape

(2, 3, 3)

In [138]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [139]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [140]:
np.expand_dims(x, axis = 2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [141]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [142]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [143]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [144]:
np.expand_dims(z, axis = 2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [145]:
np.stack((x, y, z), axis = 2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [146]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [147]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [149]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [150]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [151]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [152]:
np.hstack((a, np.expand_dims(c, axis = 1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [153]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [154]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [156]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [157]:
np.row_stack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [158]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [159]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [160]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [162]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [163]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [164]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [165]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [166]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [168]:
np.column_stack([x, 10, 20, y])

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [169]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [170]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [171]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [173]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [175]:
np.r_[3:10:3, [0] * 2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [176]:
np.r_[-1:1:6j, [0] * 2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [177]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [178]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [179]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [180]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [182]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [183]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [184]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [187]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [188]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [189]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [190]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [191]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [192]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [193]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [195]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [196]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [197]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [198]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [200]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [203]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [204]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [205]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [206]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [208]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [209]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [210]:
np.split(x, 4)

ValueError: array split does not result in an equal division

In [211]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [213]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [214]:
np.split(y, [2, 3, 4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [215]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int32)]

In [216]:
y[4:6]

array([50, 60])

In [217]:
y[6:]

array([], dtype=int32)

In [219]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [220]:
np.split(a, 3, axis = 1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [221]:
np.split(a, 4, axis = 1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [222]:
np.split(a, 5, axis = 1)

ValueError: array split does not result in an equal division

In [227]:
np.split(a, [3, 5, 7], axis = 1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [225]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [228]:
np.split(b, 3, axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [229]:
np.split(b, [2, 4, 6], axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int32)]

In [230]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [232]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [235]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [236]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [237]:
np.hsplit(a, 4)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [239]:
np.hsplit(a, 5)

ValueError: array split does not result in an equal division

In [240]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [241]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [242]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [243]:
np.vsplit(a, 2)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [244]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [245]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [246]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [247]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int32)]

In [248]:
a[1:, :]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [249]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [250]:
a[6:, :]

array([], shape=(0, 3), dtype=int32)

In [252]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [253]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [254]:
np.split(x, 2, axis = 1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [255]:
x[:, :2, :]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]])

In [256]:
x[:, 2:, :]

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])

In [257]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [258]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [259]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [260]:
np.split(x, 2, axis = 0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [261]:
x[:2, :, :]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [263]:
x[2:, :, :]

array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [264]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [273]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [267]:
np.array_split(x, 2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [268]:
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [269]:
np.array_split(x, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [270]:
np.array_split(x, 5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [274]:
np.array_split(x, [2, 4, 8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

In [275]:
a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [276]:
np.array_split(a, 2, axis = 0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [277]:
np.array_split(a, 2, axis = 1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [278]:
np.array_split(a, 4, axis = 0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [279]:
np.array_split(a, 4, axis = 1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [280]:
np.array_split(a, [2, 4], axis = 0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [281]:
np.array_split(a, [2, 4], axis = 1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [282]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [283]:
np.array_split(x, 4, axis = 2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [284]:
np.split(x, [2, 4, 5], axis = 2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [285]:
x[:, :, 5:]

array([[[ 5],
        [11]],

       [[17],
        [23]]])

In [286]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [287]:
np.dsplit(x, 2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [288]:
np.split(x, 2, axis = 2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [289]:
np.dsplit(x, 3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [290]:
np.dsplit(x, 4)

ValueError: array split does not result in an equal division

In [291]:
np.dsplit(x, [2, 4, 5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [292]:
x[:, :, 4:5]

array([[[ 4],
        [10]],

       [[16],
        [22]]])

In [293]:
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x1EF2F1D4F20

In [294]:
r = rg.random()
r

0.22733602246716966

In [295]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [296]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [297]:
rg = np.random.default_rng(12345)
r = rg.integers(low = 0, high = 10, size = 3)
r

array([6, 2, 7], dtype=int64)

In [298]:
rg.integers(1, 7, (3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]], dtype=int64)

In [299]:
rg = np.random.default_rng(seed = 42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [300]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])